apiVersion: apps/v1
kind: Deployment
metadata:
  name: woldvirtual-blockchain
  labels:
    app: woldvirtual-blockchain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: woldvirtual-blockchain
  template:
    metadata:
      labels:
        app: woldvirtual-blockchain
    spec:
      containers:
      - name: blockchain
        image: woldvirtual3d/blockchain:latest
        ports:
        - containerPort: 8545
          name: network
        - containerPort: 8546
          name: rpc
        - containerPort: 8547
          name: websocket
        - containerPort: 8548
          name: bridge
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8546"
        - name: WS_PORT
          value: "8547"
        - name: BRIDGE_PORT
          value: "8548"
        - name: BSC_RPC_URL
          value: "https://bsc-dataseed1.binance.org/"
        - name: BSC_CONTRACT_ADDRESS
          value: "0x053532E91FFD6b8a21C925Da101C909A01106BBE"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8546
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8546
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: blockchain-data
          mountPath: /app/data
        - name: blockchain-logs
          mountPath: /app/logs
      volumes:
      - name: blockchain-data
        persistentVolumeClaim:
          claimName: blockchain-data-pvc
      - name: blockchain-logs
        persistentVolumeClaim:
          claimName: blockchain-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: woldvirtual-blockchain-service
spec:
  selector:
    app: woldvirtual-blockchain
  ports:
  - name: network
    port: 8545
    targetPort: 8545
  - name: rpc
    port: 8546
    targetPort: 8546
  - name: websocket
    port: 8547
    targetPort: 8547
  - name: bridge
    port: 8548
    targetPort: 8548
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 